version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3002:3002"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend 